name: Delete Old Users

on:
  schedule:
    - cron: "0 9 * * 2"

jobs:
  delete_users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run tasks
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          DB: ${{ secrets.DB }}
        run: python tasks.py
